spring:
  output.ansi.enabled: always

  datasource:
    url: jdbc:postgresql://jelani.db.elephantsql.com:5432/terrqtcb
    username: terrqtcb
    password: 068_C8bC3aNqG1cwrinFCIhBNQeHVjNx
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect

#  h2:
#    console:
#        enabled: true
#        path: /h2-console
#  datasource:
#    url: jdbc:h2:mem:proyecto-integrador
#    username: sa
#    password: 123
#    driverClassName: org.h2.Driver
#  jpa:
#    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
#    defer-datasource-initialization: true
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

