spring:
  output.ansi.enabled: always
  h2:
    console:
        enabled: true
        path: /h2-console
  datasource:
    url: jdbc:h2:mem:proyecto-integrador
    username: sa
    password: 123
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true