spring:
  output.ansi.enabled: always

  datasource:
#    url: jdbc:postgresql://jelani.db.elephantsql.com:5432/terrqtcb
#    username: terrqtcb
#    password: 068_C8bC3aNqG1cwrinFCIhBNQeHVjNx
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true